FROM ruby:2.6-alpine
RUN apk add --no-cache build-base postgresql-dev git tzdata
RUN gem install --no-document --conservative 'nokogiri:1.13.10'
RUN gem install --no-document --conservative 'activesupport:4.2.11.3'
RUN gem install --no-document --conservative 'rails-html-sanitizer:1.4.4'
RUN gem install --no-document --conservative 'rails-dom-testing:2.0.3' 'rails-deprecated_sanitizer:1.0.4'
RUN gem install --no-document --conservative 'actionview:4.2.11.3'
RUN gem install --no-document --conservative 'actionpack:4.2.11.3' 'activerecord:4.2.11.3' 'pg:0.21.0' rspec
WORKDIR /work
